name: clang-format Check
on: [push, pull_request]
jobs:
  formatting-check:
    name: Formatting Check (${{ matrix.check-path }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check-path: ['lib', 'cli', 'web']
    steps:
    - uses: actions/checkout@v7
    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.18.0
      with:
        clang-format-version: '22'
        check-path: ${{ matrix.check-path }}
