name: Release CLI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
            submodules: true

      - name: Install GetCMake
        uses: lukka/get-cmake@v4.4.2

      - name: Install GCC
        uses: egor-tensin/setup-gcc@v2
        with:
          version: 15
          platform: x64

      - name: Configure CMake
        run: cmake -S . -B build -DBUILD_CLI=ON -DBUILD_WASM=OFF
          -DCMAKE_BUILD_TYPE=Release

      - name: Build Release
        run: cmake --build build --config Release

      - name: Upload executable
        uses: actions/upload-artifact@v7.0.1
        with:
          name: puplang-cli
          path: build/cli/puplang-cli
          archive: false
