name: Sound Table

on:
  workflow_run:
    workflows: [Release CLI]
    types:
      - completed

jobs:
  sound-table:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download CLI
        uses: actions/download-artifact@v8.0.1
        with:
          name: puplang-cli
          path: .
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make executable
        run: chmod +x puplang-cli

      - name: Generate sound table
        run: ./puplang-cli sounds -o sound_table.txt

      - name: Upload sound table
        uses: actions/upload-artifact@v7.0.1
        with:
          name: sound-table
          path: sound_table.txt
          archive: false